HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
NDELIUS_API_URL: "https://manage-my-community-sentence-and-delius-dev.hmpps.service.justice.gov.uk/"

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
